routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'QuizController@index');
Route::get('/addsection', 'QuizController@addSection')->name('quizzes.addSection');
Route::post('/savesectionquestions', 'QuizController@saveSectionQuestions')->name('quizzes.savesectionquestions');
//Route::get('/', 'QuizController@index');

Route::resource('quizzes','QuizController');
Route::get('/quizzes/{id}/addquestion/{question}', 'QuizController@addQuestion')->name('quizzes.addquestion');
Route::get('/quizzes/{id}/removequestion/{question}', 'QuizController@removeQuestion')->name('quizzes.removequestion');

Route::resource('questions', 'QuestionController');
Route::resource('questions.options','OptionController', ['except' => ['index']]);
#Route::resource("quizzes.questions","QuestionController", ['except' => ['index']]);
#Route::get('/questions', 'QuestionController@index')->name('questions.index');
Route::post('/createAnswer','AnswerQuizController@createAnswer')->name('user.answers');
Route::post('/createAnswers/{quiz_id}', 'AnswerQuizController@createAnswers')->name('user.createAnswers');
Route::post('/checkManually/{quizID}/{questionID}','AnswerQuizController@checkManualy')->name('answerquizzes.checkManually');
Route::get('/live_quiz/{id}/{round}/{question_id}/mark/{answer}/{user}/{question_number}', 'AnswerQuizController@mark_answer')->name('mark_answer');
Route::resource('answerquizzes', 'AnswerQuizController');
#Route::delete('/options/{id}/delete', 'OptionController@destroy')->name('options.destroy');
Auth::routes();

Route::get('/home', 'QuizController@index');
Route::post('/storeAnswer', 'AnswerQuizController@storeAnswer')->name('answers.store');
Route::get('/updateQuestion', 'AnswerQuizController@updateQuestion')->name('quizzes.trial');
Route::get('/answerquizzes/administer/{id}', 'AnswerQuizController@administerQuiz')->name('quizzes.administer');
Route::get('/{quizid}/nextquestion', 'AnswerQuizController@getNext')->name('quizzes.nextquestion');
Route::get('/showanswer/{quizID}/{questionID}', 'AnswerQuizController@showanswer')->name('quizzes.showanswer');
Route::get('/nextround/{quizID}', 'AnswerQuizController@nextRound')->name('quizzes.nextround');
Route::get('/welcome/{id}', 'AnswerQuizController@welcome')->name('answerquizzes.welcome');
Route::get('/endquiz/{id}', 'AnswerQuizController@endQuiz')->name('answerquizzes.end_quiz');
Route::get('/correct_answer/{quizID}/{questionID}', 'AnswerQuizController@showCorrectAnswer')->name('quizzes.showCorrectAnswer');
Route::post('/updateTime', 'AnswerQuizController@updateTime')->name('quizzes.updateTime');

resources/views/quizzes/_quiz.blade.php
<div class="form-group @if($errors->has('name')) has-error @endif">
  <label for="name-field">Name</label>
  <input type="text" id="name-field" name="name" class="form-control" value="{{ is_null(old("name")) ? $quiz->name : old("name") }}"/>
  @if($errors->has("name"))
    <span class="help-block">{{ $errors->first("name") }}</span>
  @endif
  <label for="schedule-field">Schedule</label>
 <div class="input-group date">
  <input type="text" class="form-control" id="schedule-field" name="schedule" value="{{ is_null(old("schedule")) ? $quiz->schedule : old("schedule") }}"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
</div>
  @if($errors->has("schedule"))
    <span class="help-block">{{ $errors->first("schedule") }}</span>
  @endif                  
</div>

resources/views/quizzes/add_section_modal.blade.php
<style>
    .modal-dialog {
        position: absolute;
        top: 50px;
        right: 100px;
        bottom: 0;
        left: 100px;
        z-index: 10040;
        overflow: auto;
        overflow-y: auto;
    }
    .modal-content {
        position: relative;
        max-height: 400px;
        max-width: 700px;
        padding: 15px;
    }
</style>
<div id="myModal" class="modal">
  <div class='modal-dialog'>
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">&times;</span>
      <h2>Modal Header</h2>
      <form action="{{ route('quizzes.addSection') }}" method="GET">
        <input type="hidden" name="quiz_id" value="{{$quiz->id}}">
        <input type="hidden" name="_method" value="PUT">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <label>Name of Section</label>
       <!--  <input type="text" name=""> -->
       <input type="text" name="section_name" style="color: black;">
        <button>Add</button>
      </form>
    </div>
    <div class="modal-body">
  </div>
 </div>
</div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
</div>

resources/views/quizzes/answerable_quiz.blade.php
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
</head>
<body>
  @extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Quizzes / {{$quiz->name}}</h1>
    </div>
@endsection

@section('content')
    <!--@include('error')-->

    <div class="row">
        <div class="col-md-12">
            <form action="{{ route('quizzes.update', $quiz->id) }}" method="POST">
            <label>Already shared to: </label>
            <div>
               @foreach($sharedTo as $shared)
                {{$shared->user_email}}
                @endforeach
            </div>
            <label>Share quiz to other users: </label>
            <select name="visibility[]" class="selectpicker" data-live-search="true" multiple>
              @foreach($users as $user)
                  <option value="{{$user->email}}">{{$user->name}} {{$user->email}}</option>
              @endforeach
            </select>
            <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                @include('quizzes._quiz')
                
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                 
                    <a class="btn btn-link pull-right" href="{{ route('quizzes.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading">Questions</div>
            <div class="panel-body">
              @foreach($quiz->questions as $question)
                @include('questions._show', ['question' => $question])
              @endforeach
            </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
          <div class="panel panel-info">
            <div class="panel-heading" style="height:50px;">Available Questions
              <form class="form-inline pull-right">
                <div class="form-group">
                  <input type="text" class="form-control input-sm" id="search-field" placeholder="easy">
                </div>
                <button type="submit" class="btn input-sm btn-default">Search</button>
              </form>
            </div>
            <div class="panel-body">
               @include('questions._index', ['questions' => $questions, 'quiz' => $quiz])
            </div>
          </div>
      </div>
    </div>
@endsection
@section('scripts')
  <script src="//code.jquery.com/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.input-group.date').datepicker({
      format: "yyyy-mm-dd",
      todayBtn: true,
      autoclose: true
    });
  </script>
@endsection
</body>

resources/views/quizzes/create.blade.php
@extends('layout')

@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
  <link type="text/css" href="css/new.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Quizzes / Create </h1>
    </div>
@endsection

@section('content')
    <!--@include('error')-->

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('quizzes.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                @include('quizzes._quiz')

                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('quizzes.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.input-group.date').datepicker({
      format: "yyyy-mm-dd",
      todayBtn: true,
      autoclose: true
    });
  </script>
@endsection

resources/views/quizzes/edit.blade.php
@extends('layout')

<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
</head>
<body>
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Quizzes / {{$quiz->name}}</h1>
    </div>
@endsection

@section('content')
    <div class="row">
      <div class="col-md-12">
        <form action="{{ route('quizzes.update', $quiz->id) }}" method="POST">
            @if($quiz->quiz_type == 0)
              <input type="radio" value="0" name="quiz_type" checked="">Conventional<br>
              <input type="radio" value="1" name="quiz_type">Live<br>
            @else
              <input type="radio" value="0" name="quiz_type">Conventional<br>
              <input type="radio" value="1" name="quiz_type" checked="">Live<br>
            @endif
          <!-- <p>Already shared to: </p>
          <div>
             @foreach($sharedTo as $shared)
              {{$shared->user_email}}
             @endforeach
          </div> -->

          <p>Share quiz to other users: </p>
          <select name="visibility[]" class="selectpicker" data-live-search="true" multiple>
            @foreach($users as $user)
                <option value="{{$user->email}}">{{$user->name}} {{$user->email}}</option>
            @endforeach
          </select>
              <input type="hidden" name="_method" value="PUT">
              <input type="hidden" name="_token" value="{{ csrf_token() }}">
              @include('quizzes._quiz')
              
              <div class="well well-sm">
                  <button type="submit" class="btn btn-primary">Save</button>
               
                  <a class="btn btn-link pull-right" href="{{ route('quizzes.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
              </div>
        </form>
        @if($sections)
          @foreach($sections as $section)
          <div>
            <p>{{$section->name}}</p>
            @foreach($section->questions()->get() as $question)
             @include('questions._show', ['question' => App\Question::getQuestion($question->question_id)])
            @endforeach
             <div id="<?php echo "section" . $section->id?>" ondrop="drop(event)" class="section" ondragover="allowDrop(event)" style="outline-width: 10; outline-color: black; border: solid black">Drop the questions here</div>
            <button onclick="getQuestions('section'+{{$section->id}})">Save</button>
          </div>
          @endforeach
        @endif
        <div class="row">
          <h4>Available Questions</h4>
          @foreach($questions as $question)
           <div id="<?php echo $question->id ?>" draggable="true" ondragstart="drag(event)" class = "question"> {!!$question->question!!} </div><br>
          @endforeach
          {!! $questions->render() !!}
        </div>
        
         <div class="input-group">    
            <button id = "myBtn" class = 'btn btn-success'>Add Section</button>
         </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
       <!--  <div class="panel panel-success">
            <div class="panel-heading">Questions</div>
            <div class="panel-body">
              @foreach($quiz->questions as $question)
                @include('questions._show', ['question' => $question])
              @endforeach
            </div>
        </div> -->
      </div>
    </div></br>
    <div class="row">
      <div class="col-md-12">
          <!-- <div class="panel panel-info"> -->
            <!-- <div class="panel-heading" style="height:50px;">Available Questions
              <form class="form-inline pull-right">
                <div class="form-group">
                  <input type="text" class="form-control input-sm" id="search-field" placeholder="easy">
                </div>
                <button type="submit" class="btn input-sm btn-default">Search</button>
              </form> -->
            <!-- </div> -->
            <!-- <div class="panel-body"> -->
            <!--    @include('questions._index', ['questions' => $questions, 'quiz' => $quiz]) -->
            <!-- </div> -->
          <!-- </div> -->
      </div>
    </div>
    @include('quizzes.add_section_modal')
    <script type="text/javascript">
     
    var modal = document.getElementById('myModal');

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks the button, open the modal 
    btn.onclick = function() {
        modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }

    function drag(ev) {
      ev.dataTransfer.setData("text", ev.target.id);
    }

    function allowDrop(ev) {
      ev.preventDefault();
    }
    function drop(ev) {
      console.log("hello");
      ev.preventDefault();
      var data = ev.dataTransfer.getData("text");
      var name = ev.target.className;
      console.log(name);
      if(name=='section'){
        ev.target.appendChild(document.getElementById(data));
      }
      else {
        console.log(ev.target.parentElement);
        ev.target.parentElement.appendChild(document.getElementById(data));
      }
      
    }
    function getQuestions(sectionID) {
      var parent = document.getElementById(sectionID);
      var children = parent.childNodes;
      var questions = [];
      console.log(children.length);
      for(i = 0, j=0; i<children.length; i++){
        if(children[i].className == "question"){
          questions[j++] = children[i].id;
        }
      }
      token = $('meta[name="csrf-token"]').attr('content');
      data = { "_token": "{{ csrf_token() }}", section_id: sectionID, questions: questions};
      
      $.ajax({
          type: "POST",
          url: "{{ route('quizzes.savesectionquestions') }}",
          data: data,
           async : true, // if you want wait until ajax done, you should set "async" false
          complete : function(){
              console.log("[JQUERY AJAX COMPLETE]");
          },
          success: function(response){ // What to do if we succeed
              alert("Submitted");
          },
          error: function(xhr, status, error) {
            alert("FAIL");
          }
      });
      console.log("huhu");
      //igkuha nala tanan an child of child of child
    }
    </script>
    <meta name="_token" content="{!! csrf_token() !!}" />
@endsection
@section('scripts')
 <!--  <script src="//code.jquery.com/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.input-group.date').datepicker({
      format: "yyyy-mm-dd",
      todayBtn: true,
      autoclose: true
    });
  </script>
@endsection
</body>

resources/views/quizzes/index.blade.php
@extends('layout')

@section('header')
    @if (\Session::has('success'))
    <div class="alert alert-success">
        <ul>
            <li>{!! \Session::get('success') !!}</li>
        </ul>
    </div>
    @endif
    <div class="page-hdr clearfix">
        <h1 class="fnt note rounded">
        <i class="glyphicon glyphicon-menu-down" aria-hidden="true"></i>QUIZZES
        </h1> 
            <form class="form-inline pull-right">
        <div class="form-group">
          <input type="text" class="form-control input-sm" id="search-field" placeholder="Search">
        </div>
        <div class="form-group">
            <button type="submit" class="btn input-sm btn-default">Search</button>
            <a class="btn btn-success input-sm" href="{{ route('quizzes.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </div>  
    </form>
    </div>
@endsection

@section('content')
    </br> <div class="row">
    @if($quizzes->count())
        <div class="col-md-12 tbl-header">
           
                <table class="tbl" cellpadding="0" cellspacing="0" border="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>NAME</th>
                            <th>Schedule</th>
                            <th>OPTIONS</th>
                        </tr>
                    </thead>
                </table>
        </div>

        <div class="tbl-content">
            <table class="tbl" cellpadding="0" cellspacing="0" border="0">
                    <tbody>
                        @foreach($quizzes as $quiz)
                            <tr>
                                <td>{{$quiz->id}}</td>
                                <td>{{$quiz->name}}</td>
                                <td>{{$quiz->schedule}}</td>
                                <td>
                                    <a class="btn btn-xs btn-primary" href="{{route('answerquizzes.welcome', $quiz->id)}}"><i class="glyphicon glyphicon-eye-open"></i>Start Live Quiz</a>
                                    <a class="btn btn-xs btn-primary" href="{{ route('quizzes.show', $quiz->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('quizzes.edit', $quiz->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('quizzes.destroy', $quiz->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $quizzes->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/quizzes/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
    <h1 class="fnt note rounded" style="width: 30%">
        <i class="glyphicon glyphicon-stats" aria-hidden="true"></i> {{$quiz->name}}
    </h1> 
    <a style="position: absolute; right: 190px; top: 150px;" class="btn btn-primary" href="{{ route('quizzes.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
        <form action="{{ route('quizzes.destroy', $quiz->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <a style="position: absolute; right: 270px; top: 150px;" class="btn btn-success" href="{{ route('quizzes.administer', $quiz->id) }}">Start Quiz</a>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading">Questions</div>
            <div class="panel-body">
              @foreach($quiz->questions as $question)
                @include('questions._show', ['question' => $question])
              @endforeach
            </div>
        </div>
      </div>
    </div>
@endsection