routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'QuizController@index');
Route::get('/addsection', 'QuizController@addSection')->name('quizzes.addSection');
Route::post('/savesectionquestions', 'QuizController@saveSectionQuestions')->name('quizzes.savesectionquestions');
//Route::get('/', 'QuizController@index');

Route::resource('quizzes','QuizController');
Route::get('/quizzes/{id}/addquestion/{question}', 'QuizController@addQuestion')->name('quizzes.addquestion');
Route::get('/quizzes/{id}/removequestion/{question}', 'QuizController@removeQuestion')->name('quizzes.removequestion');

Route::resource('questions', 'QuestionController');
Route::resource('questions.options','OptionController', ['except' => ['index']]);
#Route::resource("quizzes.questions","QuestionController", ['except' => ['index']]);
#Route::get('/questions', 'QuestionController@index')->name('questions.index');
Route::post('/createAnswer','AnswerQuizController@createAnswer')->name('user.answers');
Route::post('/createAnswers/{quiz_id}', 'AnswerQuizController@createAnswers')->name('user.createAnswers');
Route::post('/checkManually/{quizID}/{questionID}','AnswerQuizController@checkManualy')->name('answerquizzes.checkManually');
Route::get('/live_quiz/{id}/{round}/{question_id}/mark/{answer}/{user}/{question_number}', 'AnswerQuizController@mark_answer')->name('mark_answer');
Route::resource('answerquizzes', 'AnswerQuizController');
#Route::delete('/options/{id}/delete', 'OptionController@destroy')->name('options.destroy');
Auth::routes();

Route::get('/home', 'QuizController@index');
Route::post('/storeAnswer', 'AnswerQuizController@storeAnswer')->name('answers.store');
Route::get('/updateQuestion', 'AnswerQuizController@updateQuestion')->name('quizzes.trial');
Route::get('/answerquizzes/administer/{id}', 'AnswerQuizController@administerQuiz')->name('quizzes.administer');
Route::get('/{quizid}/nextquestion', 'AnswerQuizController@getNext')->name('quizzes.nextquestion');
Route::get('/showanswer/{quizID}/{questionID}', 'AnswerQuizController@showanswer')->name('quizzes.showanswer');
Route::get('/nextround/{quizID}', 'AnswerQuizController@nextRound')->name('quizzes.nextround');
Route::get('/welcome/{id}', 'AnswerQuizController@welcome')->name('answerquizzes.welcome');
Route::get('/endquiz/{id}', 'AnswerQuizController@endQuiz')->name('answerquizzes.end_quiz');
Route::get('/correct_answer/{quizID}/{questionID}', 'AnswerQuizController@showCorrectAnswer')->name('quizzes.showCorrectAnswer');
Route::post('/updateTime', 'AnswerQuizController@updateTime')->name('quizzes.updateTime');

app/Option.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Option extends Model
{
    //
}

app/Http/Controllers/OptionController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\OptionFormRequest;

use App\Option;
use Illuminate\Http\Request;

class OptionController extends Controller {
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$options = Option::orderBy('id', 'desc')->paginate(10);

		return view('options.index', compact('options'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$option = new Option();

		return view('options.create', compact('option'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(OptionFormRequest $request, $question)
	{
		$option = new Option();

		$option->value = $request->input("value");
        $option->answer = $request->input("answer");
        $option->question_id = $question;

		$option->save();

		return redirect()->route('questions.edit', $question )->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$option = Option::findOrFail($id);

		return view('options.show', compact('option'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$option = Option::findOrFail($id);

		return view('options.edit', compact('option'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(OptionFormRequest $request, $question, $option)
	{
		$option = Option::findOrFail($option);

		$option->value = $request->input("value");
        $option->answer = $request->input("answer");
        $option->question_id = $question;

		$option->save();
		return redirect()->route('questions.edit', $question )->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($question, $option)
	{
		$option = Option::findOrFail($option);
		$option->delete();
		return redirect()->route('questions.edit', $question )->with('message', 'Item deleted successfully.');
	}

}

resources/views/options/_create.blade.php
<style>
.wlll {
        padding: 7px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .05);
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, .05);
          background-color: #f5f5f5;
        border: 1px solid #e3e3e3;
        width: 15.5%;
        margin: 20px auto;
    }
    </style>
    <div class="panel panel-default">
    <div class="panel-body">

<div class="row">
    <div class="col-md-12">

        <form action="{{ route('questions.options.store', ['question'=>$question->id]) }}" method="POST">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">

            <label style="font-size: 15px;" for="question-field">CREATE ANOTHER OPTION?</label>
            @include('options._option')

            <div class="wlll well-sm">
                <button type="submit" class="btn btn-success">Create</button>
                <a class="btn btn-primary" href="{{ route('questions.show', $question->id) }}"><i class="glyphicon glyphicon-backward"></i> Back</a>

            </div>
        </form>

    </div>
</div>
</div>
</div>

resources/views/options/_edit.blade.php
<style>
    .wll {
        padding: 7px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, .05);
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, .05);
          background-color: #f5f5f5;
        border: 1px solid #e3e3e3;
        width: 15%;
        margin: 0 15px;
    }
    .w {
        margin-bottom: 45px;
    }
</style>
<div class="row">
  <div class="col-md-12">

      <form action="{{ route('questions.options.update', ['question'=>$question_id, 'option'=>$option->id]) }}" method="POST">
          <input type="hidden" name="_method" value="PUT">
          <input type="hidden" name="_token" value="{{ csrf_token() }}">

          @include('options._option')


          <div class="wll w well-sm">

              <button type="submit" class="btn btn-primary">Save</button>               
         
      </form>
         <form action="{{ route('questions.options.destroy', ['question'=>$question_id, 'option'=>$option->id]) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                  <input type="hidden" name="_method" value="DELETE">
                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                  <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
              </form>
          </div>
  </div>
</div>

resources/views/options/_option.blade.php
<style>
  .bttnn {
      position: absolute;
      top: 5px;
      right: 170px;
   }
   .bt {
      position: absolute;
      top: 0px;
      right: 110px;
   }  
   .btt {
      position: absolute;
      top: 0px;
      right: 54px;
   }
  
</style>
<div class="form-group @if($errors->has('answer')) has-error @endif">
   <label class="bttnn" for="answer-field">Is the below answer?</label>
    <div data-toggle="buttons">
      <label class="btn bt btn-success {{$option->answer == 1 ? 'active': ''}}">
        <input type="radio" value="1" name="answer" id="answer-field" autocomplete="off" {{$option->answer == 1 ? 'checked': ''}}> 
          True
      </label>
      <label class="btn btt btn-warning {{$option->answer == 0 ? 'active': ''}}">

        <input type="radio" value="0" name="answer" id="answer-field" autocomplete="off" {{$option->answer == 0 ? 'checked': ''}}> 
          False
      </label>
    </div>
   @if($errors->has("answer"))
    <span class="help-block">{{ $errors->first("answer") }}</span>
   @endif

</div>
<div class="form-group @if($errors->has('value')) has-error @endif">
   <label for="value-field">Value</label>
<textarea id="value-field" name="value" class="form-control">
  {{ is_null(old("value")) ? $option->value : old("value") }}
</textarea>
   @if($errors->has("value"))
    <span class="help-block">{{ $errors->first("value") }}</span>
   @endif
</div>

resources/views/options/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Options / Create </h1>
    </div>
@endsection

@section('content')
    <!--@include('error')-->

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('options.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                @include('options._option')

                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('options.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/options/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Options / Edit #{{$option->id}}</h1>
    </div>
@endsection

@section('content')
    <!--@include('error')-->

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('options.update', $option->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

                @include('options._option')
                
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('options.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/options/index.blade.php
@extends('layout')

@section('header')
    <div class="page-header clearfix">
        <h1>
            <i class="glyphicon glyphicon-align-justify"></i> Options
            <a class="btn btn-success pull-right" href="{{ route('options.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
        </h1>

    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if($options->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>VALUE</th>
                        <th>ANSWER</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($options as $option)
                            <tr>
                                <td>{{$option->id}}</td>
                                <td>{{$option->value}}</td>
                    <td>{{$option->answer}}</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('options.show', $option->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('options.edit', $option->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('options.destroy', $option->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $options->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/options/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Options / Show #{{$option->id}}</h1>
        <form action="{{ route('options.destroy', $option->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('options.edit', $option->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                <div class="form-group">
                     <label for="value">VALUE</label>
                     <p class="form-control-static">{{$option->value}}</p>
                </div>
                    <div class="form-group">
                     <label for="answer">ANSWER</label>
                     <p class="form-control-static">{{$option->answer}}</p>
                </div>
            </form>

            <a class="btn btn-link" href="{{ route('options.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection