routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'QuizController@index');
Route::get('/addsection', 'QuizController@addSection')->name('quizzes.addSection');
Route::post('/savesectionquestions', 'QuizController@saveSectionQuestions')->name('quizzes.savesectionquestions');
//Route::get('/', 'QuizController@index');

Route::resource('quizzes','QuizController');
Route::get('/quizzes/{id}/addquestion/{question}', 'QuizController@addQuestion')->name('quizzes.addquestion');
Route::get('/quizzes/{id}/removequestion/{question}', 'QuizController@removeQuestion')->name('quizzes.removequestion');

Route::resource('questions', 'QuestionController');
Route::resource('questions.options','OptionController', ['except' => ['index']]);
#Route::resource("quizzes.questions","QuestionController", ['except' => ['index']]);
#Route::get('/questions', 'QuestionController@index')->name('questions.index');
Route::post('/createAnswer','AnswerQuizController@createAnswer')->name('user.answers');
Route::post('/createAnswers/{quiz_id}', 'AnswerQuizController@createAnswers')->name('user.createAnswers');
Route::post('/checkManually/{quizID}/{questionID}','AnswerQuizController@checkManualy')->name('answerquizzes.checkManually');
Route::get('/live_quiz/{id}/{round}/{question_id}/mark/{answer}/{user}/{question_number}', 'AnswerQuizController@mark_answer')->name('mark_answer');
Route::resource('answerquizzes', 'AnswerQuizController');
#Route::delete('/options/{id}/delete', 'OptionController@destroy')->name('options.destroy');
Auth::routes();

Route::get('/home', 'QuizController@index');
Route::post('/storeAnswer', 'AnswerQuizController@storeAnswer')->name('answers.store');
Route::get('/updateQuestion', 'AnswerQuizController@updateQuestion')->name('quizzes.trial');
Route::get('/answerquizzes/administer/{id}', 'AnswerQuizController@administerQuiz')->name('quizzes.administer');
Route::get('/{quizid}/nextquestion', 'AnswerQuizController@getNext')->name('quizzes.nextquestion');
Route::get('/showanswer/{quizID}/{questionID}', 'AnswerQuizController@showanswer')->name('quizzes.showanswer');
Route::get('/nextround/{quizID}', 'AnswerQuizController@nextRound')->name('quizzes.nextround');
Route::get('/welcome/{id}', 'AnswerQuizController@welcome')->name('answerquizzes.welcome');
Route::get('/endquiz/{id}', 'AnswerQuizController@endQuiz')->name('answerquizzes.end_quiz');
Route::get('/correct_answer/{quizID}/{questionID}', 'AnswerQuizController@showCorrectAnswer')->name('quizzes.showCorrectAnswer');
Route::post('/updateTime', 'AnswerQuizController@updateTime')->name('quizzes.updateTime');

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    

    public function blankOption()
    {
        $option = new Option();
        $option->answer = 0;
    	return $option;
    }

    public function options()
    {
    	return $this->hasMany('App\Option');
    }

    public function quizzes()
    {
    	return $this->belongsToMany('App\Quiz');
    }


    public function user()
    {
    	return $this->belongsTo('App\User');
    }

    public static function getQuestion($id)
    {
        $question = Question::findOrFail($id);
        return $question;
    }

    public static function points($id){
        $question = Question::findOrFail($id);
        return $question->points;
    }
}

app/Http/Controllers/QuestionController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\QuestionFormRequest;

use App\Question;
use App\Quiz;
use Illuminate\Http\Request;
use Auth;



class QuestionController extends Controller {

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    
	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{

		$user = Auth::user();
		$questions = Question::where('user_id', $user->id)->orderBy('id', 'desc')->paginate(10);


		return view('questions.index', compact('questions'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$question = new Question();
		return view('questions.create', compact('question'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(QuestionFormRequest $request)
	{
		$question = new Question();
		$user = Auth::user();
		$question->question = $request->input("question");
		$question->round = $request->input("round");
		$question->user_id = $user->id;
		$question->answer = $request->input("answer");
		$question->save();
        if($question->round == "Difficult"){
		    return redirect()->route('questions.index', compact('question'))->with('message', 'Item created successfully.');
		}else{
		    return redirect()->route('questions.edit', compact('question'))->with('message', 'Item created successfully.');
		}
	} 

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($question)
	{
		$question = Question::findOrFail($question);
		return view('questions.show', compact('question'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($question)
	{
		$question = Question::findOrFail($question);
		return view('questions.edit', compact('question'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(QuestionFormRequest $request, $question)
	{
		$question = Question::findOrFail($question);

		$question->question = $request->input("question");
        $question->round = $request->input("round");
        $question->answer = $request->input("answer");
        $question->points = $request->input("points");
		$question->save();

		return redirect()->route('questions.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($question)
	{
		$question = Question::findOrFail($question);
		$question->delete();

		return redirect()->route('questions.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/questions/_controladd.blade.php
<a class="btn btn-xs btn-success" href="{{ route('quizzes.addquestion', ['id'=>$quiz->id, 'question'=>$question->id]) }}"><i class="glyphicon glyphicon-ok"></i> Add to Quiz</a>
<a class="btn btn-xs btn-primary" href="{{ route('questions.show', ['question'=>$question->id]) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
<a class="btn btn-xs btn-warning" href="{{ route('questions.edit', ['question'=>$question->id]) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>

resources/views/questions/_controlall.blade.php
<a class="btn btn-xs btn-primary" href="{{ route('questions.show', ['question'=>$question->id]) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
<a class="btn btn-xs btn-warning" href="{{ route('questions.edit', ['question'=>$question->id]) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
<form action="{{ route('questions.destroy', ['question'=>$question->id]) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
</form>

resources/views/questions/_index.blade.php
<div class="row">
@if($questions->count())
    <div class="col-md-12 tbl-header">
       
        <table class="tbl" cellpadding="0" cellspacing="0" border="0">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>QUESTION</th>
                    <th>ROUND</th>
                    <th>OPTIONS</th>
                </tr>
            </thead>
        </table>
    </div>
   
    <div class="tbl-content">
        <table class="tbl" cellpadding="0" cellspacing="0" border="0">
            <tbody>
                @foreach($questions as $question)
                    <tr>
                        <td>{{$question->id}}</td>
                        <td>{!! $question->question !!}</td>
                        <td>{{$question->round}}</td>
                        <td>
                                @if(isset($quiz))
                                    @include('questions._controladd')
                                @else
                                    @include('questions._controlall')
                                @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
            {!! $questions->render() !!}
             @else
            <h3 class="text-center alert alert-info">Empty!</h3>
        @endif

    </div>
</div>

resources/views/questions/_question.blade.php
<div class="form-group @if($errors->has('round')) has-error @endif">
   <label style="font-size: 15px;" for="round-field">ROUND</label>
   <select onchange="round1()" id="round" name="round" class="form-control" style="width: 30%;">

   		<option {{$question->round == 'Easy' ? 'selected': ''}}>Easy</option>
   		<option {{$question->round == 'Average' ? 'selected': ''}}>Average</option>
   		<option {{$question->round == 'Difficult' ? 'selected': ''}}>Difficult</option>
   </select>
   <label>POINTS</label>
   <input type="number" name="points">
   @if($errors->has("round"))
    <span class="help-block">{{ $errors->first("round") }}</span>
   @endif
</div>

<label style="font-size: 15px;" for="question-field">QUESTION</label>
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="form-group @if($errors->has('question')) has-error @endif">
   
        <textarea id="question-field" name="question" class="form-control" >
        {{is_null(old("question")) ? $question->question : old("question") }}
        </textarea>
        @if($errors->has("question"))
          <span class="help-block">{{ $errors->first("question") }}</span>
        @endif
    </div>
  </div>
</div>
<div id="answer" style="display: none;" >
  <label style="font-size: 15px;" for="question-field">Answer</label>
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="form-group @if($errors->has('question')) has-error @endif">
    
        
          <textarea name="answer" class="form-control" >
             {{ $question->answer }}
          </textarea>
          
      </div>
    </div>
  </div>
</div>
<script>
    $('textarea').ckeditor();
    // $('.textarea').ckeditor(); // if class is prefered.
    function round1(){
       var yourSelect = document.getElementById( "round" );
       var answerArea = document.getElementById( "answer" );
       var options = document.getElementById( "options" );
       var round = yourSelect.options[ yourSelect.selectedIndex ].value;
       if(round == "Difficult" ){
           answerArea.style.display = "block";
           options.style.display = "none";
       }else{
           answerArea.style.display = "none";
           options.style.display = "block";
        }
     } 
  </script>

resources/views/questions/_show.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-md-9">{!! $question->question !!}</div>
                    <div class="col-md-3">
                        <div class="btn-group pull-right" role="group" aria-label="...">
                            <a class="btn btn-xs btn-warning btn-group" role="group" href="{{ route('questions.edit', $question->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>

                            @if(isset($quiz))
                            <a class="btn btn-xs btn-danger" role="group" href="{{ route('quizzes.removequestion', ['id'=>$quiz->id, 'question'=>$question->id]) }}"><i class="glyphicon glyphicon-trash"></i> Remove From Quiz</a>
                            @endif
                           
                        </div>
                    </div>    
                </div>
                       
            </div>
            <div class="panel-body">
                <ul class="list-group-item">
                    @foreach($question->options as $option)
                    <li class="list-group-item">{!! $option->value !!}</li>
                    @endforeach
                </ul>
            </div>
        </div> 
    </div>
</div>

resources/views/questions/create.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Questions / Create </h1>
    </div>
@endsection

@section('content')
    <!--@include('error')-->

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('questions.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                @include('questions._question')
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('questions.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection
@section('scripts')
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
  <script>
    $('.date-picker').datepicker({
    });
  </script>
@endsection

resources/views/questions/edit.blade.php
@extends('layout')
@section('css')
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/css/bootstrap-datepicker.css" rel="stylesheet">
@endsection
@section('header')
    <style>
        .bttn {
            position: absolute;
            top: 25px;
            right: 95px;
        }
        .btton {
            position: absolute;
            top: 25px;
            right: 15px;
        } 
        .bttonn {
            position: absolute;
            top: 30px;
            right: 165px;
        }   
    </style>
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-edit"></i> Questions / Edit #{{$question->id}}</h1>
    </div>
@endsection

@section('content')
    <!--@include('error')-->

    <div class="row">
        <div class="col-md-12">



            <form action="{{ route('questions.update', ['question'=>$question->id]) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                @include('questions._question')
                
                <!-- <div class="well well-sm"> -->
                <label style="font-size: 15px;" class="bttonn" for="question-field">Save this question?</label>
                    <button type="submit" class="btn bttn btn-success">Save</button>
                    <a class="btn btton btn-primary pull-right" href="{{ route('questions.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                <!-- </div> -->
            </form>
        </div>
    </div><br>
    @if($question->round != "Difficult")
       <div id="options" style="display: block;">
        <label style="font-size: 15px;" for="question-field">OPTIONS</label>
            <div class="panel panel-default">
                <div class="panel-body">
                    @foreach($question->options as $option)
                        @include('options._edit', ['option'=>$option, 'question_id'=>$option->question_id])
                    @endforeach
                    @include('options._create', ['option'=>$question->blankOption(), 'question_id'=>$question->id])
                </div>
            </div>
        </div>
    @endif
@endsection
@section('scripts')
  <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
  <script src="/vendor/unisharp/laravel-ckeditor/adapters/jquery.js"></script>
  <script>
    $('.date-picker').datepicker({

    }); 

  </script>
@endsection

resources/views/questions/index.blade.php
@extends('layout')

@section('header')
    <div class="page-hdr clearfix">
        <h1 class="fnt note rounded" style="width: 25%"><i class="glyphicon glyphicon-align-justify" aria-hidden="true"></i> QUESTIONS</h1> 
         	<form class="form-inline pull-right">
		        <div class="form-group">
		          <input type="text" class="form-control input-sm" id="search-field" placeholder="Search">
		        </div>
		        <div class="form-group">
		        	<button type="submit" class="btn input-sm btn-default">Search</button>
			        <a class="btn input-sm btn-success" href="{{ route('questions.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
			    </div>  
	      	</form>
    </div><br>
@endsection

@section('content')
    @include('questions._index')
@endsection

resources/views/questions/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Question # {{$question->id}}</h1>
</div>
@endsection

@section('content')
    @include('questions._show', ['question'=>$question])
@endsection